/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccordionItem: typeof import('./src/components/UI/Accordion/AccordionItem.vue')['default']
    Avatar: typeof import('./src/components/UI/avatar.vue')['default']
    Blanket: typeof import('./src/components/Popover/blanket.vue')['default']
    Button: typeof import('./src/components/UI/button.vue')['default']
    Confirm: typeof import('./src/components/Popover/Confirm.vue')['default']
    Footer: typeof import('./src/components/Layout/footer.vue')['default']
    Input: typeof import('./src/components/UI/input.vue')['default']
    List: typeof import('./src/components/UI/List/List.vue')['default']
    ListItem: typeof import('./src/components/UI/List/ListItem.vue')['default']
    More: typeof import('./src/components/Popover/More.vue')['default']
    Navbar: typeof import('./src/components/Layout/Navbar.vue')['default']
    Pill: typeof import('./src/components/UI/pill.vue')['default']
    PricingToggle: typeof import('./src/components/UI/pricingToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesCard: typeof import('./src/components/Sales/SalesCard.vue')['default']
    Steps: typeof import('./src/components/Register/steps.vue')['default']
    Support: typeof import('./src/components/Popover/Support.vue')['default']
    SupportLink: typeof import('./src/components/Content/SupportLink.vue')['default']
    TextArea: typeof import('./src/components/UI/textArea.vue')['default']
    UpdateApi: typeof import('./src/components/Popover/UpdateApi.vue')['default']
  }
}
